### ISSUE TITLE
Missing Points of Interest

### ISSUE THREAD

**Issue by amatissart** [QwantResearch/qwantmaps#83]
Many feedbacks reported POIs that would be nice to import in Qwant Maps tiles and search engine.

- [x] **`craft=`** joiner, carpenter, brewery, shoemaker... (#76, #23)
- [x] **`shop=`** seafood, funeral_directors (#73, #44 ), and potentially any shop
- [x] `amenity=driving_school` (#43)
- [x] `recycling_type=center` and/or `amenity=recycling` (#39)
- [x] `amenity=charging_station` (#37)
- [x] `leisure=fitness_centre` (#35)
- [x] `amenity=coworking_space` (#12)
- [x] `landuse=military` (https://github.com/CanalTP/mimirsbrunn/issues/315)
- [x] `water=stream_pool`(https://github.com/CanalTP/mimirsbrunn/issues/315)

Most of these should probably be added to our "poi" layer in https://github.com/QwantResearch/openmaptiles/

**Comment by yotamN** [comment]
It would be nice to import those POIs but there will always be more tags, won't it be better to have a fallback for unknown tags? If they have name they are still useful

**Comment by francois2metz** [comment]
> It would be nice to import those POIs but there will always be more tags, won't it be better to have a fallback for unknown tags? If they have name they are still useful

I took a look at it,  should be doable on the openmaptiles sides, but harder to have a good look on the mapbox-gl side as there is no way to have a fallback on an icon if no one are matching.

**Comment by francois2metz** [comment]
- [ ] amenity=car_rental

**Comment by nlehuby** [comment]
- [ ] amenity=toy_library (has been approved by the OSM community recently)

**Comment by dkurzaj** [comment]
- [ ] amenity=social_facility

Example: https://www.openstreetmap.org/node/7169012373

It represents some non profits organizations which provide social services. I think it would be nice to be able to orient people in need to this type of structures.

**Comment by MatthieuOSM** [comment]
shop=tea
shop=sewing
shop=fireplace

craft=roofer

healthcare=physiotherapist
healthcare:speciality=osteopathy;physiotherapist

amenity=social_facility
social_facility=group_home

office=estate_agent

**Comment by mathis-kdio** [comment]
Anything new?

**Comment by raphodn** [comment]
Similar to `amenity=social_facility`, there is `office=association` and `office=ngo` missing

Example: Emmaüs Connect in Paris (nodes [6099306717](https://www.openstreetmap.org/node/6099306717) & [6099306716](https://www.openstreetmap.org/node/6099306716))

**Comment by MatthieuOSM** [comment]
shop=farm usefull one for covid19

**Comment by Charlotte-Ziegler** [comment]
Thanks for these missing points. We are gradually adding them and we'll add shop=farm next week.

**Comment by dkurzaj** [comment]
shop=games

For shops selling board games.

Example : https://www.openstreetmap.org/node/4448735295

**Comment by amatissart** [comment]
All suggested items are now visible on Qwant Maps, including most OSM objects with the tags `amenity`, `shop`, `craft`, `leisure` or `office`.

I am closing this issue. Feel free to open a new issue if you notice any problem with a specific item, or to suggest other types of POIs that could be included.

**Comment by matkoniecz** [comment]
Is it intentional that it is still pinned?

**Comment by amatissart** [comment]
No additional feedback have been received recently about missing POIs, so this issue can be unpinned indeed.

**Comment by TheAdventurer64** [comment]
Could `shop=mall` be added?

**Comment by matkoniecz** [comment]
@TheAdventurer64 

This is a closed issue. Such comments are likely to be missing.
